# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb1c7377ba6046838669b2019742d04f03a66d96a91e35d034f42cc65fbe50ed09932cd8a99fdb483914e9b14fec2cb8b060c99160940126bb7ab88b4ea7525

test:
  secret_key_base: 34e0388adedba61ea1ec45107bfa85dd34bb18a4f87bd43bf20a4a694d523607b27c0973042b369db49e4dbc3f55b36c16070dffe8d1e3d96fe2915d13a9e8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
